spring.datasource.url: jdbc:mysql://localhost:3306/the_blog_schema?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 5O4vx85sd{4}
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.open-in-view: true

spring.jpa.show-sql: false

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db-migrations/changelog.xml

spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB

blog:
  hostAddress: https://skillbox-the-blog.herokuapp.com
  captchaCodeLifecycle: 60
  intervalForClearingCaptchaCodesInMilliseconds: 60000
  title: the-blog
  subtitle: Рассказы разработчиков
  phone: +7 905 655-41-53
  email: platonov230388@gmail.com
  copyright: Юрий Платонов
  copyrightFrom: 2021
  mailSmtpAuth: true
  mailSmtpSslEnable: true
  mailSmtpHost: smtp.gmail.com
  mailSmtpPort: 465




