spring.datasource.url: jdbc:mysql://localhost:3306/the_blog_schema?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: 5O4vx85sd{4}
spring.jpa.hibernate.ddl-auto: none

spring.jpa.show-sql: false

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db-migrations/changelog.xml

blog.title: the-blog
blog.subtitle: Рассказы разработчиков
blog.phone: +7 905 655-41-53
blog.email: platonov230388@gmail.com
blog.copyright: Юрий Платонов
blog.copyrightFrom: 2021

